export const test = [{
    name: 'Faided, Fat, Greedy Woman',
    location: "Meilee Area > The Lizard's Mouth > * Santa Barbara Bouldering > Santa Barbara > Central Coast > California",
    URL: 'https://www.mountainproject.com/route/105953395/faided-fat-greedy-woman',    
    rating: 2.8,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: null,
    'Area Latitude': 34.5021,
    'Area Longitude': -119.86624,
    description: 'Exit the cave on a series of challenging slopers.',
    protection: 'none',      
    num_votes: 34,
    image: 'https://mountainproject.com/assets/photos/climb/105953398_medium_1558029363.jpg?cache=1701314922'       
  },
  {
    name: 'The Crystal Groove',
    location: 'Enlightenment Ridge > Pine Mountain > Hwy 33/Ojai Bouldering > Hwy 33/Ojai > Central Coast > California',
    URL: 'https://www.mountainproject.com/route/108972738/the-crystal-groove',
    rating: 3.4,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: 12,
    'Area Latitude': 34.63555,
    'Area Longitude': -119.31105,
    description: 'Technical, burly, and all around wonderful pine mountain slopers. High start with a right hand dish and and do some foot magic to hit the higher left hand. Top out with some slapping!',
    protection: 'pad to wipe yo shoes',
    num_votes: 19,
    image: 'https://mountainproject.com/assets/photos/climb/112227869_medium_1494327684.jpg?cache=1702072066'       
  },
  {
    name: 'Wimberries',      
    location: 'Tut Boulder > Buttermilks Main > Buttermilk Country > Bishop Area > Sierra Eastside > California',   
    URL: 'https://www.mountainproject.com/route/107024502/wimberries',
    rating: 2.9,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: 15,
    'Area Latitude': 37.329, 
    'Area Longitude': -118.5773,
    description: 'A pretty good line starting with a sit on the southwest corner of the Tut Boulder, left of King Tut.     Do a couple of hard moves on slopers to get started then work your way up the technical slab.',
    protection: 'A pad or two.',
    num_votes: 34,
    image: null
  },
  {
    name: 'Oh My',
    location: 'Treasure Chest Boulder > Treasure Cove > Castle Peak > Donner/Truckee Bouldering > I-80 Corridor > Lake Tahoe > California',      
    URL: 'https://www.mountainproject.com/route/110746378/oh-my',
    rating: 2.7,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: null,
    'Area Latitude': 39.34037,
    'Area Longitude': -120.36574,
    description: 'Sit down start between the trees, in the deep overhang, climb the obvious line up and slightly right.',
    protection: 'Crashpads', 
    num_votes: 36,
    image: 'https://mountainproject.com/assets/photos/climb/117828249_medium_1570163750.jpg?cache=1570772999'       
  },
  {
    name: 'Kaya’s Pensive',  
    location: 'Pensive Pool > South Yuba River: 49 Crossing > Auburn and Grass Valley > I-80 Corridor > Lake Tahoe > California',
    URL: 'https://www.mountainproject.com/route/116138476/kayas-pensive',
    rating: 4,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: 17,
    'Area Latitude': 39.29662,
    'Area Longitude': -121.09368,
    description: 'Beautiful climb on positive incuts to a somewhat exposed top out, perfect height. Bring at least four pads. Start crossed low on the arete with your left hand on the lower textured sloper and right hand on the positive squareish edge - with good feet, move up left to the positive incut crimp, bust out left again to the next edge, square up, then do another hardish move out left that requires somewhat of a dyno to the jug, climb straight up keeping more right/true to the arete. I think it’s around V5, but it might be easier for those taller people who don’t need to move so dynamically.',
    protection: 'At least 4 pads unless you are confident.',
    num_votes: 6,
    image: 'https://mountainproject.com/assets/photos/climb/116138487_medium_1543212206.jpg?cache=1612673214'       
  },
  {
    name: 'Hell Awaits',     
    location: 'Purgatory Boulder > Putah Creek > Wine Country/Northeast Bay > San Francisco Bay Area > California', 
    URL: 'https://www.mountainproject.com/route/107812054/hell-awaits',
    rating: 3.6,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: 15,
    'Area Latitude': 38.51657,
    'Area Longitude': -122.05583,
    description: 'Start from high holds and make a move up to some jugs. From here figure out how to get through the cryptic face sequence to better holds just below the lip. An easy top out awaits.   The low start from opposing side pulls is V7',
    protection: 'Pad and spotter',
    num_votes: 17,
    image: 'https://mountainproject.com/assets/photos/climb/118227286_medium_1578502924.jpg?cache=1579367549'       
  },
  {
    name: 'Milano Munchkin', 
    location: 'Ginja Ninja > Rainbow > Donner/Truckee Bouldering > I-80 Corridor > Lake Tahoe > California',        
    URL: 'https://www.mountainproject.com/route/119263497/milano-munchkin',
    rating: 3.1,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: null,
    'Area Latitude': 39.30887,
    'Area Longitude': -120.51262,
    description: 'Sit start on good slot holds in the cave. Pull some big moves between jugs and work out left to finish the same as for Ginja Ninja. The top is a little mossy, but there is a relatively clear path up and right.',   
    protection: '1 or 2 pads should be sufficient',       
    num_votes: 29,
    image: null
  },
  {
    name: 'Cream Horn',      
    location: 'Ice Caves > Sad Boulders > Volcanic Tablelands (Happy/Sad Boulders) > Bishop Area > Sierra Eastside > California',
    URL: 'https://www.mountainproject.com/route/106322827/cream-horn',
    rating: 4,
    'Your Stars': -1,        
    'Route Type': 'Boulder', 
    grade: 'V4',
    pitches: 1,
    height: 18,
    'Area Latitude': 37.42254,
    'Area Longitude': -118.43364,
    description: 'Climb the off-width crack squeezing past the Chef boulder at one point.  The landing becomes better up higher.   The grade is a guess -- Kevin suggested 5.11/5.12, which for an off-width is going to be nastier than the V0 suggested in the Bishop guide.   This is one of the prouder crack problems in Bishop.',
    protection: 'Pads and hubris.',
    num_votes: 6,
    image: 'https://mountainproject.com/assets/photos/climb/114314282_medium_1525046810.jpg?cache=1702072979'       
  }]